# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "About Us"
  url = "#about"
  weight = 10

[[main]]
  name = "Tutorials"
  url = "courses/"
  weight = 20

[[main]]
  name = "Insights"
  url = "#posts"
  weight = 25

[[main]]
  name = "Projects"
  url = "#projects"
  weight = 30

[[main]]
  name = "Publications"
  url = "#publications"
  weight = 40

[[main]]
  name = "Team"
  url = "#team"
  weight = 50

[[main]]
  name = "Connect"
  url = "#contact"
  weight = 70

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.

# [[main]]
#   name = "CV"
#   url = "static/files/Somsirsa_Resume.pdf"
#   weight = 80
